### ISSUE TITLE
Assertion failed: (!GDKinmemory())

### ISSUE THREAD

**Issue by bmmcq** [hannesmuehleisen/MonetDBLite-C#6]
As title, when i tried to load 100,000 records, the db worked properly.  While I doubled the inputs, this error was thrown. I'm sure that there is enough memory on my computer. 
So what's the problem ? 

Here is the code : 
``` c

static const char* USER_VISIT = "CREATE TABLE user_visit (sourceId BIGINT,destId BIGINT,sourceIp VARCHAR(116),destURL VARCHAR(100),visitDate DATE,adRevenue FLOAT,userAgent VARCHAR(256),countryCode CHAR(3),languageCode CHAR(6),searchWord VARCHAR(32),duration INT);";

int main() {
    char* err = 0;
    void* conn = 0;
    struct timespec start, end;
    monetdb_result* result = 0;
    size_t r, c;

    err = monetdb_startup(NULL, 0, 0);// NULL for in-memory mode
    if (err != 0) {
        error(err);
    }

    conn = monetdb_connect();
    if (conn == NULL) {
        error("Connection failed");
    }

    err = monetdb_query(conn, USER_VISIT, 1, NULL, NULL, NULL);
    if (err != 0) {
        error(err);
    }

    clock_gettime(CLOCK_MONOTONIC_RAW, &start);
    err = monetdb_query(conn, "COPY INTO user_visit FROM '/Users/chenqiangmcq/user_visit_10000.csv' DELIMITERS ',';", 1, NULL, NULL, NULL);
    if (err != 0) {
        error(err);
    }

... ...
```
And the error message in detail : 
>
Assertion failed: (!GDKinmemory()), function BATmsync, file src/gdk/gdk_storage.c, line 681

**Comment by hannes** [comment]
Can you share the data file? I just tried reproducing this with a file I re-constructed from your schema and it works fine. 

Here is the R script I used:
````R
n <- 200000
rndstr <- function(n, len) vapply(rep(1, n), function(x) paste(sample(c(0:9, letters, LETTERS), len, replace=TRUE), collapse=""), "character")

df <- data.frame(sourceId=seq(1,n), destId=seq(1,n), sourceIp=rndstr(n, 115), destURL=rndstr(n, 100), visitDate=rep(Sys.Date(), n), adRevenue=rep(0.0, n), userAgent=rndstr(n, 256), countryCode=rndstr(n, 3), languageCode=rndstr(n, 6), searchWord=rndstr(n, 32), duration=rep(0, n), stringsAsFactors=FALSE)

fn <- tempfile()
write.table(df, fn, row.names=F, col.names=F, sep=",", quote=F)

library(DBI)
con <- dbConnect(MonetDBLite::MonetDBLite(), ":memory:")

dbExecute(con, "CREATE TABLE user_visit (sourceId BIGINT,destId BIGINT,sourceIp VARCHAR(116),destURL VARCHAR(100),visitDate DATE,adRevenue FLOAT,userAgent VARCHAR(256),countryCode CHAR(3),languageCode CHAR(6),searchWord VARCHAR(32),duration INT)")

dbExecute(con, sprintf("COPY INTO user_visit FROM '%s' DELIMITERS ','", fn))
````

Also, what's your Operating system version, MonetDBLite version etc.?

**Comment by bmmcq** [comment]
Ok , the dataset is from : https://amplab.cs.berkeley.edu/benchmark/. I only use the data of the "UserVisits";  
My Operating system is : 
"Darwin MacBook-Pro Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64"
I compiled my monetdblite from the source : https://github.com/hannesmuehleisen/MonetDBLite-C/master. 
I will change the branch and try again . 
Thanks.

**Comment by hannes** [comment]
did the "try again" change anything?

**Comment by bmmcq** [comment]
no, i tried other branches, and change to linux system,  but there are the same errors : 

sql_db: src/gdk/gdk_storage.c:681: BATmsync: Assertion `!GDKinmemory()' failed.
Execute batch load : COPY INTO user_visit FROM '/beimian/sql_db/build/uservisit' DELIMITERS ',';bash-4.2# ^C
bash-4.2# uname -a
Linux 0cb271306e8f 2.6.32-220.23.2.ali1089.el5.x86_64 #1 SMP Fri Jun 14 10:52:15 CST 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hannes** [comment]
Okay, thanks. Can you also see what happens when you use an on-disk database, e.g. using an empty folder as first parameter to `monetdb_startup`?

**Comment by bmmcq** [comment]
On-disk database works well. After data loaded, the total size of the database directory is 2.3G : 

![image](https://user-images.githubusercontent.com/32241292/38301117-33f96858-3831-11e8-92f8-e5b231e87eab.png)

and the available memory in my machine is : 

![image](https://user-images.githubusercontent.com/32241292/38301172-5d0d89ea-3831-11e8-9942-6d74aba99568.png)

and my gcc version is 4.9.2 . 

Hope these will be helpful for you .

**Comment by hannes** [comment]
Thanks. And a direct link to the file you used would help too.

**Comment by bmmcq** [comment]
The data file i used is from  https://amplab.cs.berkeley.edu/benchmark/,  and it can be accessed from the aws too.  You should install "s3cmd" tool first  :  
``` shell 
sudo apt-get install s3cmd
s3cmd sync s3://big-data-benchmark/pavlo/text-deflate/1node/ .
for i in ./*.deflate; do echo $i; zlib-flate -uncompress < $i; done  > uservisit_1_node.csv
```

the total data may be large, you can limit to 30 million; 

Thanks;

**Comment by hannes** [comment]
The `echo` needed to be removed from the unpacking command. Also, I needed to remove the first two columns from the schema. I took the first 30M lines from the file as suggested. Was able to reproduce, so great.

**Comment by hannes** [comment]
Should be fixed in `master` branch.
