### ISSUE TITLE
progress callback data pointer not to be released

### ISSUE THREAD

**Issue by danz68** [hannesmuehleisen/MonetDBLite-C#9]
The (possible) allocated memory for the passed data pointer belongs to the application and should not be freed in monetdblite unregister code.

void monetdb_register_progress(monetdb_connection conn, monetdb_progress_callback callback, void* data);

```
void monetdb_unregister_progress(monetdb_connection conn) {
	Client c = (Client) conn;
	if (!MCvalid(c)) {
		return;
	}
	MT_lock_set(&c->progress_lock);
	c->progress_callback = NULL;
	**// if(c->progress_data)
		// free(c->progress_data);**
	c->progress_data = NULL;
	MT_lock_unset(&c->progress_lock);
}
```

**Comment by hannes** [comment]
Good point, happy to review a PR.
